name:                maze-solver
version:             0.1.0.0
github:              "karlfroldan/maze-solver"
license:             BSD3
author:              "Karl Frederick Roldan"
maintainer:          "kroldan@gbox.adnu.edu.ph"
copyright:           "2021 Karl Frederick Roldan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/karlfroldan/maze-solver#readme>

dependencies:
- base >= 4.7 && < 5
- algebraic-graphs > 0.3 && <= 0.5
- parallel > 3.0.0.0 && <= 3.5.0.0
- threepenny-gui >= 0.5.0.0 && <= 1.0.0.0
- hip >= 1.5.0.0 && <= 1.6.0.0

library:
  source-dirs: src

executables:
  maze-solver:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maze-solver

tests:
  maze-solver-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maze-solver
